# Progress Entry: Physical Layer Standardization & Topology Optimization

## Date
April 11, 2026

## Summary
Executed a strategic adjustment to the physical network layout. After a technical review of the traffic flow, the Test PC was re-routed to connect directly to the **Cisco L3 Switch** rather than utilizing a transit path through the consumer-grade router. This ensures maximum Layer 2 visibility and eliminates potential routing bottlenecks.

## Physical Layer Specifications
* **Media Procured**: 100 ft Ultra Clarity Cat 6 Ethernet.
* **Standards Compliance**: Rated for 10Gbps / 550MHz; Outdoor/Indoor durability.
* **Path Validation**: Measured a ~78 ft required run. Staying well within the **100-meter (328 ft) limit** for TIA/EIA-568 Ethernet standards ensures zero signal degradation.
* **Status**: Procurement complete; physical deployment pending.

## Architectural Rationale & Topology Shift
The previous design relied on a router-intermediated path for the test environment. The updated plan bypasses the router for the following technical reasons:

1. **Layer 2 Observability**: Direct switch connectivity allows for the implementation of **SPAN/Mirror ports**. This is critical for capturing raw packet data from the Test PC for ingestion into **Suricata** and **Wireshark**.
2. **Security & Segmentation**: Direct connection to the Cisco switch enables the application of **VLAN 30 (Lab/SOC)** port-level ACLs and MAC-based 'sticky' security.
3. **Repurposed Hardware**: The existing router will be transitioned to **Access Point (AP) mode** to provide isolated guest Wi-Fi, removing it from the primary wired data path.



## Endpoint Integration Status (Test PC)
The Test PC (Windows 10 Pro) is currently in the staging phase:
* **Protocol Analysis**: Wireshark installed and verified.
* **Endpoint Telemetry**: **Sysmon** deployed with a custom configuration for process and network event tracking.
* **Log Aggregation**: **Splunk Universal Forwarder** installed; service account preparation is underway to facilitate log delivery to the indexer on VLAN 10.

## Next Steps
* **Physical Deployment**: Finalize the 100 ft cable run and verify link integrity (1Gbps auto-negotiation).
* **Peripheral Integration**: Local connection of the test printer to the Test PC for endpoint-based print logging.
* **Documentation**: Update the master topology diagrams to reflect the direct-to-core connection model.

---
> **Engineering Note**: This change prioritizes "Visibility First" architecture. By moving the test node to the switch, we ensure that every packet generated by the "attacker" or "victim" machines is visible to our security stack before it ever reaches a routing boundary.
